import Link from "next/link";
import { Shield } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0f1a2e] px-6 py-12">
      <div className="max-w-3xl mx-auto">
        {/* Logo */}
        <Link href="/" className="flex items-center gap-2 mb-10">
          <Shield className="w-6 h-6 text-red-500" />
          <span className="text-xl font-bold text-white">Redline<span className="text-red-500">AI</span></span>
        </Link>

        <div className="bg-[#162035] border border-[#1e3050] rounded-2xl p-8">
          <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
          <p className="text-slate-400 text-sm mb-8">Last updated: April 2026</p>

          <div className="prose prose-invert prose-sm max-w-none space-y-6 text-slate-300 leading-relaxed">

            <div className="bg-[#1e3050] rounded-xl p-4 border border-[#2a4070]">
              <p className="text-white font-semibold">This service is operated by Pactbug.</p>
              <p className="text-slate-400 text-sm mt-2">
                RedlineAI is operated by Pactbug. Payments are processed by{" "}
                <span className="text-white">Paddle.com Market Limited</span>{" "}
                acting as our Merchant of Record under the trade name{" "}
                <span className="text-white">Trytimeback</span>. Your card statement may show
                &ldquo;Trytimeback&rdquo; or &ldquo;Paddle.net&rdquo; for charges related to RedlineAI.
              </p>
            </div>

            <section>
              <h2 className="text-lg font-semibold text-white mb-2">1. Acceptance of Terms</h2>
              <p>By accessing or using RedlineAI (&ldquo;the Service&rdquo;), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-2">2. Description of Service</h2>
              <p>RedlineAI is an AI-powered contract analysis tool that helps users identify potentially risky clauses in legal documents. The Service is provided for informational purposes only and does not constitute legal advice.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-2">3. Not Legal Advice</h2>
              <p>RedlineAI is not a law firm and does not provide legal advice. The analysis generated by our AI is for informational purposes only. You should consult a qualified attorney before making any legal decisions based on the Service&apos;s output.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-2">4. User Accounts</h2>
              <p>You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately of any unauthorized use of your account. We reserve the right to terminate accounts that violate these Terms.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-2">5. Acceptable Use</h2>
              <p>You agree not to:</p>
              <ul className="list-disc list-inside space-y-1 mt-2 text-slate-400">
                <li>Upload content that is illegal, harmful, or infringes on third-party rights</li>
                <li>Attempt to reverse engineer or circumvent the Service</li>
                <li>Use the Service for any unlawful purpose</li>
                <li>Share your account credentials with others</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-2">6. Subscription and Payment</h2>
              <p>Paid plans are billed on a monthly basis. Payments are processed securely through Paddle. By subscribing, you authorize us to charge your payment method on a recurring basis until you cancel.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-2">7. Refund Policy</h2>
              <p>We offer a 14-day refund policy. Please see our <Link href="/refund" className="text-red-400 hover:text-red-300">Refund Policy</Link> for full details.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-2">8. Intellectual Property</h2>
              <p>The Service, including its design, features, and content, is owned by Pactbug and is protected by intellectual property laws. You retain ownership of the documents you upload; however, you grant us a limited license to process them for the purpose of providing the Service.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-2">9. Disclaimer of Warranties</h2>
              <p>The Service is provided &ldquo;as is&rdquo; without warranties of any kind. We do not guarantee the accuracy, completeness, or reliability of the AI-generated analysis.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-2">10. Limitation of Liability</h2>
              <p>To the maximum extent permitted by law, Pactbug shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-2">11. Changes to Terms</h2>
              <p>We reserve the right to modify these Terms at any time. We will notify users of significant changes via email or a notice on the Service. Continued use of the Service after changes constitutes acceptance of the new Terms.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-2">12. Contact</h2>
              <p>For questions about these Terms, please contact us at <a href="mailto:admin@pactbug.com" className="text-red-400 hover:text-red-300">admin@pactbug.com</a>.</p>
            </section>
          </div>
        </div>

        <div className="flex gap-6 justify-center mt-8 text-sm text-slate-500">
          <Link href="/privacy" className="hover:text-slate-300">Privacy Policy</Link>
          <Link href="/refund" className="hover:text-slate-300">Refund Policy</Link>
          <Link href="/" className="hover:text-slate-300">Back to Home</Link>
        </div>
      </div>
    </div>
  );
}
