/* ------------------------------------------------------------------ */
/*  RedlineAI – Generated Contract PDF export                          */
/* ------------------------------------------------------------------ */

export interface ExtractedQuote {
  providerName: string;
  providerContact: string;
  providerAddress: string;
  clientName: string;
  clientContact: string;
  clientAddress: string;
  serviceDescription: string;
  totalAmount: string;
  paymentTerms: string;
  deliveryDate: string;
  additionalTerms: string;
}

export async function downloadContractPDF(
  contractText: string,
  filename = "service-agreement"
) {
  const { default: jsPDF } = await import("jspdf");

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const PAGE_W = 210;
  const PAGE_H = 297;
  const MARGIN = 22;
  const CONTENT_W = PAGE_W - MARGIN * 2;
  const FOOTER_Y = PAGE_H - 12;
  let y = MARGIN;

  /* ── Header ── */
  doc.setFillColor(15, 26, 46);
  doc.rect(0, 0, PAGE_W, 16, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("RedlineAI", MARGIN, 10);

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(180, 195, 215);
  doc.text("Service Agreement", MARGIN + 30, 10);

  doc.text(
    new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }),
    PAGE_W - MARGIN,
    10,
    { align: "right" }
  );

  y = 26;

  /* ── Body ── */
  const lines = contractText.split("\n");
  doc.setTextColor(20, 30, 50);

  const checkPage = (need = 8) => {
    if (y + need > FOOTER_Y - 6) {
      doc.addPage();
      y = MARGIN;
    }
  };

  for (const line of lines) {
    const trimmed = line.trim();

    // Title (the very first SERVICE AGREEMENT line)
    if (trimmed === "SERVICE AGREEMENT") {
      checkPage(14);
      doc.setFontSize(16);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(185, 28, 28);
      doc.text(trimmed, PAGE_W / 2, y + 4, { align: "center" });
      y += 12;
      continue;
    }

    // Section heading: lines like "1. SCOPE OF WORK"
    if (/^\d+\.\s+[A-Z][A-Z\s]+$/.test(trimmed)) {
      checkPage(12);
      y += 3;
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(15, 23, 42);
      doc.text(trimmed, MARGIN, y);
      // Underline
      doc.setDrawColor(229, 62, 62);
      doc.setLineWidth(0.6);
      doc.line(MARGIN, y + 1.2, MARGIN + 30, y + 1.2);
      y += 7;
      continue;
    }

    // PROVIDER: / CLIENT: blocks
    if (trimmed.startsWith("PROVIDER:") || trimmed.startsWith("CLIENT:")) {
      checkPage(7);
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(15, 23, 42);
      doc.text(trimmed, MARGIN, y);
      y += 5.5;
      continue;
    }

    // Empty line → small gap
    if (trimmed === "") {
      y += 3;
      continue;
    }

    // Regular paragraph text
    doc.setFontSize(9.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(40, 50, 65);
    const wrapped = doc.splitTextToSize(trimmed, CONTENT_W) as string[];
    for (const w of wrapped) {
      checkPage(6);
      doc.text(w, MARGIN, y);
      y += 5;
    }
  }

  /* ── Footer on every page ── */
  const pageCount = doc.getNumberOfPages();
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p);
    doc.setDrawColor(200, 210, 225);
    doc.setLineWidth(0.3);
    doc.line(MARGIN, FOOTER_Y - 4, PAGE_W - MARGIN, FOOTER_Y - 4);
    doc.setFontSize(7);
    doc.setTextColor(100, 116, 139);
    doc.setFont("helvetica", "normal");
    doc.text("Generated by RedlineAI · getredlineai.com", MARGIN, FOOTER_Y);
    doc.text(`Page ${p} of ${pageCount}`, PAGE_W - MARGIN, FOOTER_Y, { align: "right" });
  }

  doc.save(`${filename}.pdf`);
}
